# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

# SEO settings
title: UTransForM
description: "Neue Technologien in der Raumforschung"
keywords: "Kassel, Universität, Projekt, Seminar, Forschung, Geografie, Stadtplanung, Raumplanung"

# Site settings
url: http://utransform.github.io
baseurl: ""
# baseurl: ""

# Author settings
author:
  name      : UTransForM
  email     : utransform@uni-kassel.de
  url       : https://utransform.github.io/
  github    : http://github.com/utransform

# google_analytics: UA-52446115-1

# comments
